# Generated by Django 5.0.3 on 2024-05-06 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('address_complement', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('license_number', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', upload_to='vehicles/')),
                ('type', models.CharField(choices=[('voiture', 'Voiture'), ('scouter', 'Scouter')], default='voiture', max_length=20)),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20)),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique')], default='essence', max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('imat', models.CharField(max_length=9)),
                ('fleet_id', models.IntegerField(unique=True)),
                ('kilometer', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('rented', 'A dispo'), ('maintenance', 'En maintenance')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('waiting', "En attente d'EDL"), ('pending', 'En cours'), ('over', 'Clôturé'), ('payed', 'Payé')], default='waiting', max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, choices=[('cdd', 'CDD'), ('cdi', 'CDI'), ('formation', 'Formation'), ('interim', 'Intérim'), ('aided_contract', 'Contrat aidé'), ('job_seeking', 'Recherche d’emploi'), ('part_time', 'Alternance')], null=True)),
                ('max_kilometer', models.IntegerField(default=None, null=True)),
                ('price', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('start_kilometer', models.IntegerField()),
                ('end_kilometer', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beneficiary')),
            ],
        ),
    ]
