# Generated by Django 5.0.3 on 2024-04-03 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('address_complement', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('license_number', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='kilometer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('waiting', 'en attente de paiement'), ('pending', 'en cours'), ('over', 'terminé')], default='waiting', max_length=100)),
                ('start_kilometer', models.IntegerField()),
                ('end_kilometer', models.IntegerField(default=None, null=True)),
                ('price', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.beneficiary')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
            ],
        ),
    ]
