# Generated by Django 5.0.3 on 2024-05-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ended_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
