# Generated by Django 5.0.3 on 2024-04-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_name_car_brand_contract_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='modele',
        ),
    ]
