# Generated by Django 5.0.3 on 2024-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contract_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('waiting', "En attente d'EDL"), ('pending', 'En cours'), ('over', 'Clôturé'), ('payed', 'Payé')], default='pending', max_length=100),
        ),
    ]
