# Generated by Django 5.0.3 on 2024-04-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_model_car_modele'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique')], default='essence', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('scouter', 'Scouter')], default='voiture', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='imat',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='car',
            name='modele',
            field=models.CharField(max_length=50),
        ),
    ]
