# Generated by Django 5.0.3 on 2024-05-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('voiture', 'Voiture'), ('scouter', 'Scooter')], default='voiture', max_length=20),
        ),
    ]
