# Generated by Django 5.0.3 on 2024-04-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_car_color_car_fleet_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Vehicle',
        ),
    ]
