# Generated by Django 5.0.3 on 2024-04-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_car_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('rented', 'Louée'), ('maintenance', 'En maintenance')], default='available', max_length=20),
        ),
    ]
