# Generated by Django 5.0.3 on 2024-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='license_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
