# Generated by Django 5.0.3 on 2024-05-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_beneficiary_license_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
