# Generated by Django 5.0.3 on 2024-05-16 20:54

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_beneficiary_archived_contract_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='archived',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='parking',
            field=models.ForeignKey(default=api.models.Parking.get_default_parking_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vehicles', to='api.parking'),
        ),
    ]
