# Generated by Django 5.0.3 on 2024-04-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_contract_comment_contract_discount_contract_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='car',
            new_name='vehicle',
        ),
    ]
