# Generated by Django 5.0.3 on 2024-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_car_contract_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='vehicles/'),
        ),
    ]
