# Generated by Django 5.0.3 on 2024-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_payment_edited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='depositPaymentMode',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('card', 'Card')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='deposit_check_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
