# Generated by Django 5.0.3 on 2024-09-13 21:28

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contract_depositpaymentmode_and_more'),
        ('core', '0004_rename_actions_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='action',
            field=models.ForeignKey(default=core.models.Action.get_default_action_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='beneficiaries', to='core.action'),
        ),
        migrations.AddField(
            model_name='contract',
            name='action',
            field=models.ForeignKey(default=core.models.Action.get_default_action_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='contracts', to='core.action'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='action',
            field=models.ForeignKey(default=core.models.Action.get_default_action_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vehicles', to='core.action'),
        ),
    ]
