# Generated by Django 5.0.3 on 2026-05-10 16:27

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_fix_default_parking_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='parking',
            field=models.ForeignKey(default=api.models.Parking.get_default_parking_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vehicles', to='api.parking'),
        ),
    ]
