# Generated by Django 5.0.3 on 2026-05-11 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_vehicle_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='renewed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='api.contract'),
        ),
    ]
