# Generated by Django 5.0.3 on 2024-07-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0004_bug_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='reporter_have_been_notified',
            field=models.BooleanField(default=False),
        ),
    ]
