# Generated by Django 5.0.3 on 2026-06-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('voiture', 'Voiture'), ('2_roues', '2 roues'), ('les_deux', 'Les deux')], default='les_deux', max_length=10)),
                ('km_periodicity', models.PositiveIntegerField(blank=True, help_text='Périodicité kilométrique (km)', null=True)),
                ('month_periodicity', models.PositiveIntegerField(blank=True, help_text='Périodicité temporelle (mois)', null=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Si vrai, le dépassement déclenche le passage automatique en maintenance')),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
