# Generated by Django 5.0.3 on 2026-06-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_initial_catalog_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct_alert_days', models.PositiveIntegerField(default=7, help_text='Nombre de jours avant expiration CT pour déclencher une alerte')),
                ('wear_alert_threshold', models.PositiveSmallIntegerField(default=4, help_text="Niveau d'usure (sur 10) en-dessous duquel une alerte est générée")),
                ('wear_critical_threshold', models.PositiveSmallIntegerField(default=3, help_text="Niveau d'usure (sur 10) en-dessous duquel le véhicule passe en maintenance")),
                ('open_intervention_alert_days', models.PositiveIntegerField(default=1, help_text="Délai (jours) après lequel une fiche d'intervention non finalisée génère une alerte")),
                ('km_max_without_intervention', models.PositiveIntegerField(default=8000, help_text='Km sans intervention validée après lesquels une alerte est générée')),
            ],
            options={
                'verbose_name': 'Configuration de maintenance',
                'verbose_name_plural': 'Configuration de maintenance',
            },
        ),
    ]
