# Generated by Django 5.0.3 on 2026-06-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_taskcatalog_vehicle_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceconfig',
            options={'permissions': [('view_dashboard', 'Peut accéder au tableau de bord garage'), ('view_vehicle', 'Peut voir les véhicules dans le module garage'), ('manage_intervention', "Peut créer et gérer les fiches d'intervention"), ('manage_inspection', 'Peut créer et gérer les fiches de contrôle intermédiaire'), ('correct_mileage', 'Peut corriger un kilométrage erroné'), ('override_maintenance_block', "Peut forcer le passage d'un véhicule en disponible malgré un blocage maintenance")], 'verbose_name': 'Configuration de maintenance', 'verbose_name_plural': 'Configuration de maintenance'},
        ),
    ]
