# Generated by Django 5.0.3 on 2026-06-14 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_renewal_contract'),
        ('garage', '0007_alter_maintenanceconfig_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceconfig',
            options={'permissions': [('view_dashboard', 'Peut accéder au tableau de bord garage'), ('view_vehicle', 'Peut voir les véhicules dans le module garage'), ('manage_intervention', "Peut créer et gérer les fiches d'intervention"), ('manage_inspection', 'Peut créer et gérer les fiches de contrôle intermédiaire'), ('override_maintenance_block', "Peut forcer le passage d'un véhicule en disponible malgré un blocage maintenance")], 'verbose_name': 'Configuration de maintenance', 'verbose_name_plural': 'Configuration de maintenance'},
        ),
        migrations.CreateModel(
            name='MileageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('contract', 'Contrat'), ('intervention', "Fiche d'intervention"), ('inspection', 'Fiche de contrôle'), ('correction', 'Correction'), ('migration', 'Migration initiale')], max_length=20)),
                ('correction_reason', models.TextField(blank=True)),
                ('is_corrected', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mileage_entries', to=settings.AUTH_USER_MODEL)),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='garage.mileageentry')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_entries', to='api.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'permissions': [('correct_mileage', 'Peut corriger un kilométrage erroné')],
                'indexes': [models.Index(fields=['vehicle', '-date'], name='garage_mile_vehicle_f168b1_idx')],
            },
        ),
    ]
