# Generated by Django 5.0.3 on 2026-07-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_mileageentry_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileageentry',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text="Référence générique vers l'objet à l'origine de l'entrée (ex: id du contrat quand source est contract_start/contract_end)", null=True),
        ),
        migrations.AlterField(
            model_name='mileageentry',
            name='source',
            field=models.CharField(choices=[('contract', 'Contrat (historique)'), ('contract_start', 'Contrat — régularisation à la création'), ('contract_end', 'Contrat — clôture/retour'), ('intervention', "Fiche d'intervention"), ('inspection', 'Fiche de contrôle'), ('correction', 'Correction'), ('migration', 'Migration initiale')], max_length=20),
        ),
    ]
