# Generated by Django 5.0.3 on 2026-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0011_mileageentry_source_id_alter_mileageentry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileageentry',
            name='source',
            field=models.CharField(choices=[('contract', 'Contrat (historique)'), ('contract_start', 'Contrat — régularisation à la création'), ('contract_end', 'Contrat — clôture/retour'), ('intervention', "Fiche d'intervention"), ('inspection', 'Fiche de contrôle'), ('correction', 'Correction'), ('migration', 'Migration initiale'), ('creation', 'Création du véhicule'), ('manual_edit', 'Modification manuelle')], max_length=20),
        ),
    ]
