services:
  backend:
    container_name: "mobilite-backend"
    image: ghcr.io/assogarrigues/platerformemobilite_back:latest
    restart: no
    ports:
      - "3005:8000"
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - external
      - mobilite-internal
    env_file:
      - .env
    volumes:
      - staticfiles:/backend/static
      - mediafiles:/backend/media
      - ./db_backups:/backend/db_backups

  nginx:
    container_name: "mobilite-nginx"
    image: ghcr.io/assogarrigues/platerformemobilite_front:latest
    restart: unless-stopped
    ports:
      - "8214:80"
    networks:
      - external
      - mobilite-internal
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - staticfiles:/staticfiles
      - mediafiles:/mediafiles

  postgres:
    container_name: "mobilite-db"
    image: bitnami/postgresql:14
    restart: unless-stopped
    networks:
      - mobilite-internal
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    hostname: ${DB_ADDR}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      start_period: 5s
      interval: 30s
      timeout: 5s
      retries: 5


networks:
  mobilite-internal:
    driver: bridge
    internal: true
  external:
    driver: bridge

volumes:
  staticfiles:
  mediafiles:
  pg-data: