# Generated by Django 5.0.3 on 2024-09-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='actions',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.actions'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currently_connected_users', to='core.actions'),
        ),
    ]
