# Generated by Django 5.0.3 on 2024-09-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actions_user_actions_user_current_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
    ]
